[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$C6G01przPmeM0VpL6T0nBA$LRQADp0FCZ3wRz1R5l5yEqENIxM9CoN/P9iUy0kLbgzeBd.2Z8GRNNfdwnBybkddjWNOliZIcecNH5HTgiH1Vg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

