import Link from 'next/link'
import { Badge } from '@/components/ui'
import { Cell, ResourceList } from '@/components/resource-list'
import { listAssessments } from '@/lib/odoo/models/assessment'
import { m2oLabel } from '@/lib/odoo/types'

export const metadata = { title: 'Assessments · Async School' }

const TONE = {
  draft: 'muted',
  open: 'live',
  submitted: 'neutral',
  returned: 'neutral',
  approved: 'neutral',
  locked: 'solid',
  published: 'solid',
} as const

export default function AssessmentsPage() {
  return (
    <ResourceList
      title="Assessments"
      subtitle="Mark lists are generated by Odoo from subject enrolments — never typed in by hand."
      load={() => listAssessments({ limit: 50 })}
      columns={['Assessment', 'Class', 'Subject', 'Term', 'Date', 'Out of', 'Marks', 'Status']}
      emptyTitle="No assessments visible"
      emptyHint="A teacher sees assessments for their own exact assignment only."
      renderRow={(row) => (
        <>
          <Cell strong>
            <Link href={`/assessments/${row.id}`} className="hover:text-action-blue">
              {row.name}
            </Link>
          </Cell>
          <Cell>{m2oLabel(row.class_id)}</Cell>
          <Cell>{m2oLabel(row.subject_id)}</Cell>
          <Cell>{m2oLabel(row.term_id)}</Cell>
          <Cell>{row.date}</Cell>
          <Cell numeric>{row.max_mark}</Cell>
          <Cell numeric>{row.mark_count}</Cell>
          <Cell>
            <Badge tone={TONE[row.state as keyof typeof TONE] ?? 'neutral'}>
              {String(row.state || '—')}
            </Badge>
          </Cell>
        </>
      )}
    />
  )
}
