name: Odoo Audit Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  audit-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Run Odoo Audit
        run: |
          python scripts/audit_odoo.py


      - name: Display Audit Report
        run: |
          cat reports/audit_report.md